version: "3.9"
    
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo

  example-app:
    depends_on:
      - mongo
    image: dichi/example-app
    ports:
      - 3000:3000
    restart: always
    environment:
      MONGO_SERVER: mongodb://root:admin@mongo:27017/

volumes:
  mongo_data: {}